development:
  adapter: postgresql
  encoding: unicode
  database: tsunami_dev
  pool: 5
  username: tsunami
  password: password
test:
  adapter: postgresql
  encoding: unicode
  database: tsunami_test
  pool: 5
  username: tsunami
  password: password
production:
  adapter: postgresql
  encoding: unicode
  database: tsunami_prod
  pool: 5
  username: tsunami
  password: password